global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "livekit-agent"
    static_configs:
      - targets: ["localhost:9100"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 4s
